**This template is provided as a guide to your Jupyter notebook report. You should edit all sections as you see fit. Don't forget to replace the title too!**

# Our Data Mining Pilot Study and Plan

## Background

*Describe the organization and its operations, operational environment, analytical needs, etc.*

Philips test

## Problem description

*Describe the problem that the organization is facing and the research question it needs answered.*

*Replace the contents of this cell with your own text.*

## Data collection

*Document your data collection process and the properties of the data here. Implement, using Python code, to load and preprocess your selected dataset.*

*Replace the contents of this cell with your own text.*

In [6]:
# Run this cell to import the modules and set up some stuff
import pandas as pd
import matplotlib
%matplotlib inline
matplotlib.pyplot.rcParams['figure.figsize'] = [10, 6]

In [22]:
name_basics = pd.read_csv(
    "https://uppsalasystemvetare.se/name.basics.tsv", 
    encoding="utf-8", sep="\t", 
    dtype={'nconst': str, 'primaryName': str, 'birthYear': str, 'deathYear': str, 'primaryProfession': str, 'knownForTitles': str}
)

In [23]:
title_basics = pd.read_csv(
    "https://uppsalasystemvetare.se/title.basics.tsv", 
    encoding="utf-8", sep="\t", 
    dtype={'tconst': str, 'titleType': str, 'primaryTitle': str, 'originalTitle': str, 'isAdult': int, 'startYear': str, 'endYear': str, 'runtimeMinutes': str, 'genres': str}
)

In [24]:
title_principals = pd.read_csv(
    "https://uppsalasystemvetare.se/title.principals.tsv", 
    encoding="utf-8", sep="\t", 
    dtype={'tconst': str, 'ordering': int, 'nconst': str, 'category': str, 'job': str, 'characters': str}
)

In [25]:
title_ratings = pd.read_csv(
    "https://uppsalasystemvetare.se/title.ratings.tsv", 
    encoding="utf-8", sep="\t", 
    dtype={'tconst': str, 'averageRating': float, 'numVotes': int}
)

In [26]:
title_principals

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Herself""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0374658,cinematographer,director of photography,\N
3,tt0000002,1,nm0721526,director,\N,\N
4,tt0000002,2,nm1335271,composer,\N,\N
5,tt0000003,1,nm0721526,director,\N,\N
6,tt0000003,2,nm5442194,producer,producer,\N
7,tt0000003,3,nm1335271,composer,\N,\N
8,tt0000003,4,nm5442200,editor,\N,\N
9,tt0000004,1,nm0721526,director,\N,\N
10,tt0000004,2,nm1335271,composer,\N,\N
11,tt0000005,1,nm0443482,actor,\N,"[""Blacksmith""]"
12,tt0000005,2,nm0653042,actor,\N,"[""Assistant""]"
13,tt0000005,3,nm0005690,director,\N,\N
14,tt0000005,4,nm0249379,producer,producer,\N
15,tt0000006,1,nm0005690,director,\N,\N
16,tt0000007,1,nm0179163,actor,\N,\N
17,tt0000007,2,nm0183947,actor,\N,\N
18,tt0000007,3,nm0005690,director,\N,\N
19,tt0000007,4,nm0374658,director,\N,\N
20,tt0000007,5,nm0249379,producer,producer,\N
21,tt0000008,1,nm0653028,actor,\N,"[""Sneezing Man""]"
22,tt0000008,2,nm0005690,director,\N,\N
23,tt0000008,3,nm0374658,cinematographer,\N,\N
24,tt0000009,1,nm0063086,actress,\N,"[""Miss Geraldine Holbrook (Miss Jerry)""]"
25,tt0000009,2,nm0183823,actor,\N,"[""Mr. Hamilton""]"
26,tt0000009,3,nm1309758,self,\N,"[""Himself - the Director of the New York Centr..."
27,tt0000009,4,nm0085156,director,\N,\N
28,tt0000010,1,nm0525910,director,\N,\N
29,tt0000011,1,nm3692297,actor,\N,"[""Acrobats""]"
...,...,...,...,...,...,...
30788668,tt9270348,2,nm9614552,self,\N,"[""Himself - Guest""]"
30788669,tt9270348,3,nm10189306,self,\N,"[""Himself - Guest""]"
30788670,tt9270352,1,nm1507806,self,\N,"[""Himself - Host""]"
30788671,tt9270352,2,nm2735324,self,\N,"[""Himself""]"
30788672,tt9270354,1,nm9715585,director,\N,\N
30788673,tt9270354,2,nm4657202,cinematographer,\N,\N
30788674,tt9270354,3,nm7823895,editor,lead editor,\N
30788675,tt9270354,4,nm5901121,editor,\N,\N
30788676,tt9270364,1,nm9240020,self,\N,"[""Himself - Host""]"
30788677,tt9270368,1,nm9503097,director,\N,\N
30788678,tt9270368,2,nm0848936,producer,producer,\N
30788679,tt9270368,3,nm9108327,cinematographer,\N,\N
30788680,tt9270368,4,nm7634625,cinematographer,\N,\N
30788681,tt9270368,5,nm10255369,cinematographer,\N,\N
30788682,tt9270372,1,nm6944582,actress,\N,\N
30788683,tt9270372,2,nm1970007,actress,\N,\N
30788684,tt9270372,3,nm3561247,director,\N,\N
30788685,tt9270372,4,nm7195251,producer,producer,\N
30788686,tt9270378,1,nm2038226,actor,\N,"[""Grunt #4""]"
30788687,tt9270378,2,nm9361270,actress,\N,"[""Maya""]"
30788688,tt9270378,3,nm8557133,actor,\N,"[""Leader""]"
30788689,tt9270378,4,nm8297088,director,\N,\N
30788690,tt9270378,5,nm8776916,producer,producer,\N
30788691,tt9270378,6,nm8181498,cinematographer,\N,\N
30788692,tt9270378,7,nm8682612,production_designer,\N,\N
30788693,tt9270382,1,nm5851797,self,\N,"[""Himself""]"
30788694,tt9270382,2,nm10216891,cinematographer,\N,\N
30788695,tt9270388,1,nm5851797,actor,\N,\N
30788696,tt9270388,2,nm10216890,cinematographer,\N,\N
30788697,tt9270388,3,nm10216891,cinematographer,\N,\N

## Data analysis

*Document you choice and motivation for selected data mining method(s) here. Choose a data mining method(s) to use in Python code to perform an analysis of your chosen dataset. Describe why you chose the method(s) and what interesting things you have found from the analysis.*

*Replace the contents of this cell with your own text.*

In [3]:
# Add your own code

## Evaluation of results

*Document an evaluation your analysis results and describe how potentially actionable they are.*

*Replace the contents of this cell with your own text.*

In [ ]:
# Add your own code

## Schedule and description of project plan

*Rough schedule for the project beyond the pilot study presented in 3-5. This does not have to be advanced, you can simply provide an estimate based upon reported schedules for similar projects in the literature.*

*Replace the contents of this cell with your own text.*

## Ethical aspects that need to be considered

*Are there ethical aspects that need to be considered? Are there legal implications (e.g., personal data / GDPR)? Are there implications if the case organization is a business, public authority, or nonprofit entity?*

*Replace the contents of this cell with your own text.*